name: trans
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  utils:
    path: utils

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  pull_to_refresh: ^1.6.0
  dio: 3.0.8
  http: ^0.12.1
  intl: ^0.16.0
  html_unescape: ^1.0.1+3
  #  flutter_html: ^0.10.4
  shared_preferences: ^0.5.7+2
  share: ^0.6.4+2
  firebase_core: ^0.4.0+8
  firebase_messaging: ^5.1.3
  flutter_native_admob: ^2.1.0
  flutter_spinkit: ^4.1.2+1
  cached_network_image: ^2.2.0+1
  url_launcher: ^5.4.7
  pin_code_fields: ^3.0.1
  image_picker: ^0.6.6+4
  flutter_inappwebview: ^3.3.0+3
  geolocator: ^5.3.2+2
  latlong: ^0.6.1
  location: ^3.0.2
  flutter_image_compress: ^0.6.7
  path: ^1.6.4
  solid_bottom_sheet: ^0.1.9
  google_maps_flutter: ^0.5.28+1
  socket_io_client: ^0.9.10
  carousel_slider: ^2.2.1
  badges: ^1.1.1
  bouncing_widget: ^1.2.0
  flutter_polyline_points: ^0.2.1
  ads: ^1.7.3
  flutter_slidable: ^0.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  utils:
    path: utils

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/images/about.jpeg
    - assets/images/home.png
    - assets/images/news.png
    - assets/images/earn_money.png
    - assets/images/setting.png
    - assets/images/shopping.png
    - assets/images/home_background.png
    - assets/images/shopping_background.jpg
    - assets/images/train.jpg
    - assets/images/post_placeholder.png
    - assets/images/deco_logo.png
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/vn.png
    - assets/images/au.png
    - assets/images/avatar_empty.png
    - assets/images/green_check.png
    - assets/images/success.png
    - assets/images/cart.png

    - assets/images/coming_soon.png
    - assets/images/house.png
    - assets/images/job.png
    - assets/images/tour_guide.png
    - assets/images/transportation.jpg

    - assets/images/change_info.png
    - assets/images/change_password.png
    - assets/images/logout.png
    - assets/images/version.png
    - assets/images/personal.png
    - assets/images/link.png
    - assets/images/cod.png
    - assets/images/online.png

    - assets/images/failure.png
    - assets/images/back.png
    - assets/images/search.png
    - assets/images/add.png
    - assets/images/empty_box.png
    - assets/images/marker_box.png
    - assets/images/coin.png

  # Font
  fonts:
    - family: DecoNewsIcons
      fonts:
        - asset: fonts/DecoNewsIcons.ttf
